name: Python build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 3"

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'Macaulay2/M2'
          ref: 'development'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13-dev'
      - name: Install dependencies
        run : |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2 # for mathicgb
          sudo apt-get install -y 4ti2 cohomcalg coinor-csdp fflas-ffpack gfan libboost-dev libboost-regex-dev libboost-stacktrace-dev libcdd-dev libeigen3-dev libflint-dev libfrobby-dev libgc-dev libgdbm-dev libgivaro-dev libglpk-dev libgtest-dev libmathic-dev libmathicgb-dev libmemtailor-dev libmpfi-dev libmpfr-dev libmps-dev libnauty2-dev libnormaliz-dev libntl-dev libopenblas-dev libsingular-dev libtbb-dev libtool-bin lrslib nauty normaliz singular-data topcom
      - name: Build Macaulay2
        run: |
          cd M2
          make
          cd BUILD
          export LDFLAGS="-L$(python3 -c 'import sysconfig; print(sysconfig.get_config_vars("LIBDIR")[0])')"
          ../configure --with-system-gc --with-system-memtailor --with-system-mathic --with-system-mathicgb --with-python --enable-documentation=info
          make PACKAGES=Python
      - name: Test Macaulay2
        run: make -C BUILD/Macaulay2/packages check-Python
