name: Python build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 3"

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
          - 3.13
          - 3.14
          - 3.15-dev
    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'Macaulay2/M2'
          ref: 'development'
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run : |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2 # for mathicgb
          sudo apt-get install -y 4ti2 cohomcalg coinor-csdp fflas-ffpack gfan libboost-dev libboost-regex-dev libboost-stacktrace-dev libcdd-dev libeigen3-dev libflint-dev libfrobby-dev libgc-dev libgdbm-dev libgivaro-dev libglpk-dev libgtest-dev liblzma-dev libmathic-dev libmathicgb-dev libmemtailor-dev libmpfi-dev libmpfr-dev libmps-dev libnauty-dev libnormaliz-dev libntl-dev libopenblas-dev libreadline-dev libsingular-dev libtbb-dev libtool-bin lrslib msolve nauty normaliz singular-data topcom
      - name: Build Macaulay2
        run: |
          cd M2
          ./autogen.sh
          cd BUILD/build
          export LDFLAGS="-L$(python3 -c 'import sysconfig; print(sysconfig.get_config_vars("LIBDIR")[0])')"
          ../../configure --with-system-libs --enable-documentation=info
          make PACKAGES=Python
      - name: Test Macaulay2
        run: make -C M2/BUILD/build/Macaulay2/packages check-Python
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ matrix.version }}-artifacts
          path: |
            M2/M2/BUILD/build/config.log
            M2/M2/BUILD/build/libraries/*/build/*/config.log
            M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
            /tmp/M2-*/*.tmp
            /tmp/M2-*/*.m2
