name: RHEL build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 5"

jobs:
  rhel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution: ['rockylinux', 'almalinux']
        version: [8, 9]
    container:
      image: ${{ matrix.distribution }}:${{ matrix.version }}
    steps:
      - name: Install dependencies
        run: |
          dnf install -y 'dnf-command(config-manager)'
          if [[ ${{ matrix.version }} = 8 ]]
          then
            dnf config-manager --set-enabled powertools
          else
            dnf config-manager --set-enabled crb
          fi
          dnf install -y epel-release
          dnf -y install autoconf automake bison boost-devel bzip2 cmake diffutils eigen3 flex gc-devel gcc-c++ gcc-gfortran gdbm-devel git glpk-devel gmp-devel lapack-devel libffi-devel libtool libxml2-devel make mpfr-devel ncurses-devel openblas-devel patch python3-devel readline-devel tbb-devel time which xz-devel zlib-devel
      - name: Clone repository
        run: git clone https://github.com/d-torrance/M2 -b html-check-links --depth 1
      - name: Build Macaulay2
        run: |
          cd M2/M2
          ./autogen.sh
          cd BUILD
          ../configure --with-system-gc --enable-download
          make
      - name: Test Macaulay2
        run: make -C M2/M2/BUILD check
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.distribution }}-${{ matrix.version }}-artifacts
          path: |
            M2/M2/BUILD/config.log
            M2/M2/BUILD/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
            /tmp/M2-*/*.tmp
            /tmp/M2-*/*.m2
