name: RHEL build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 4"

jobs:
  rhel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - rockylinux
          - almalinux
        release:
          - 8
          - 9
          - 10
    steps:
      - uses: actions/checkout@v5
        with:
          repository: Macaulay2/M2
          ref: development
      - name: Build RPM
        run: |
          cd M2/BUILD/rpm
          make rpm DISTRIBUTION=${{ matrix.distribution == 'rockylinux' && 'rockylinux/rockylinux' || matrix.distribution }} RELEASE=${{ matrix.release }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fedora-${{ matrix.version }}-artifacts
          path: |
            M2/BUILD/rpm/rpmbuild-*/BUILD/Macaulay2-*/M2/config.log
            M2/BUILD/rpm/rpmbuild-*/BUILD/Macaulay2-*/M2/libraries/*/build/*/config.log
            M2/BUILD/rpm/rpmbuild-*/BUILD/Macaulay2-*/M2/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
            M2/BUILD/rpm/rpmbuild-*/RPMS/*/*.rpm
