name: RHEL build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 5"

jobs:
  rhel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution: ['rockylinux', 'almalinux']
        version: [8, 9, 10]
    container:
      image: ${{ matrix.distribution == 'rockylinux' && 'rockylinux/rockylinux' || matrix.distribution }}:${{ matrix.version }}
    steps:
      - name: Install dependencies
        run: |
          dnf -y install autoconf automake bison boost-devel bzip2 cmake diffutils flex flexiblas-devel gcc-c++ gcc-gfortran git gmp-devel libffi-devel libtool libxml2-devel make mpfr-devel ncurses-devel patch python3-devel readline-devel tbb-devel time which xz-devel zlib-devel
      - name: Clone repository
        run: git clone https://github.com/Macaulay2/M2 -b development --depth 1
      - name: Build Macaulay2
        run: |
          cd M2/M2
          ./autogen.sh
          cd BUILD/build
          ../../configure
          make
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.distribution }}-${{ matrix.version }}-artifacts
          path: |
            M2/M2/BUILD/build/config.log
            M2/M2/BUILD/build/libraries/*/build/*/config.log
            M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
            /tmp/M2-*/*.tmp
            /tmp/M2-*/*.m2
