name: OpenSUSE build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 0"

jobs:
  suse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [leap, tumbleweed]
    container:
      image: opensuse/${{ matrix.version }}
    steps:
      - name: Install dependencies
        run: |
          zypper install -y 4ti2 arb-devel autoconf automake bison boost-devel cddlib-devel cmake e-antic-devel eigen3-devel fflas-ffpack-devel flex flint-devel gc-devel gcc gcc-c++ gcc-fortran gdbm-devel gfan git givaro-devel glpk-devel gmp-devel gtest gzip libboost_regex-devel libboost_stacktrace-devel libfactory-devel libfactory-gftables libffi-devel libtool libxml2-devel lrslib make mpfi-devel mpfr-devel nauty ncurses-devel normaliz normaliz-devel ntl-devel openblas-devel patch pkg-config python3-devel tar tbb-devel xz-devel zlib-devel
      - name: Clone repository
        run: git clone https://github.com/Macaulay2/M2 -b development --depth 1
      - name: Build Macaulay2
        run: |
          cd M2/M2/BUILD/build
          ../../autogen.sh
          ../../configure --with-system-gc
          make
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opensuse-${{ matrix.version }}-artifacts
          path: |
            M2/M2/BUILD/build/config.log
            M2/M2/BUILD/build/libraries/*/build/*/config.log
            M2/M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
            /tmp/M2-*/*.tmp
            /tmp/M2-*/*.m2
